config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ramen_store

  resources :ramen_stores

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ramen.rb
class Ramen < ApplicationRecord
end

app/models/ramen_detail.rb
class RamenDetail < ApplicationRecord

end

app/models/ramen_store.rb
class RamenStore < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/store_detail.rb
class StoreDetail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  @ramen_store = Ramen_store.all
 end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @maps = Map.all
  end
end

app/controllers/ramen_controller.rb
class RamenController < ApplicationController
  
end

app/controllers/ramen_stores_controller.rb
class RamenStoresController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @posts = pagy(RamenStore.all)
  end

  def show
    @ramen_store = RamenStore.where(id: :id)
  end

  def new
    @ramen_store = RamenStore.new
  end

  def edit
    @ramen_store
  end

  def create
    @ramen_store = RamenStore.new(user_params)
    @ramen_store.save
    redirect_to ramen_stores_path
  end

  def user_params
    params.require(:ramen_store).permit(:store_name, :store_number, :latitude, :longitude)
  end

  def destroy
    @ramen_store = RamenStore.find(params[:id])
    @ramen_store.destroy
    redirect_to ramen_stores_path
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    render json:@stores
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :adress, :yubin, :num, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/ramen_helper.rb
module RamenHelper
end

app/helpers/ramen_stores_helper.rb
module RamenStoresHelper
  include Pagy::Frontend
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/map/index.html.erb
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css">
</head>
<body>
    <% @maps.each do |map| %>
        <%= map.name %><br>
    <% end %>
</body>

app/views/ramen/_form.html.erb
<%= form_with(model: raman, local: true) do |form| %>
  <% if raman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(raman.errors.count, "error") %> prohibited this raman from being saved:</h2>

      <ul>
      <% raman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ramen/edit.html.erb
<h1>Editing Raman</h1>

<%= render 'form', raman: @raman %>

<%= link_to 'Show', @raman %> |
<%= link_to 'Back', ramen_path %>

app/views/ramen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ramen</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ramen.each do |raman| %>
      <tr>
        <td><%= link_to 'Show', raman %></td>
        <td><%= link_to 'Edit', edit_raman_path(raman) %></td>
        <td><%= link_to 'Destroy', raman, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raman', new_raman_path %>

app/views/ramen/new.html.erb
<h1>New Raman</h1>

<%= render 'form', raman: @raman %>

<%= link_to 'Back', ramen_path %>

app/views/ramen/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_raman_path(@raman) %> |
<%= link_to 'Back', ramen_path %>

app/views/ramen_stores/_form.html.erb
<%= form_with(model: ramen_store, local: true) do |form| %>

    <div class="form-group row">
      <%= form.label :store_name, class: 'col-12 col-form-label' %>
      <div class="col-12 col-sm-10">
        <%= form.text_field :store_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :store_number, class: 'col-12 col-form-label' %>
      <div class="col-12 col-sm-10">
        <%= form.text_field :store_number, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :latitude, class: 'col-12 col-form-label' %>
      <div class="col-12 col-sm-10">
        <%= form.text_field :latitude, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :longitude, class: 'col-12 col-form-label' %>
      <div class="col-12 col-sm-10">
        <%= form.text_field :longitude, class: 'form-control' %>
      </div>
    </div>

    <div class="actions d-flex justify-content-center">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/ramen_stores/index.html.erb
<%= button_to "新規作成", {controller: 'ramen_stores', action: 'new'}, {method: :get, class:"btn btn-primary"} %>

<div class="mx-auto">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">store_name</th>
      <th scope="col">store_number</th>
      <th scope="col">latitude</th>
      <th scope="col">longitude</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
        <tr>
          <th scope="row"><%= post.id %></th>
          <td><%= link_to post.store_name, "ramen_stores/#{post.id}" %></td>
          <td><%= post.store_number %></td>
          <td><%= post.latitude %></td>
          <td><%= post.longitude %></td>
          <td><%= link_to "delete", "ramen_stores/#{post.id}", method: :delete, data: {confirm: "削除します"} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<% if @posts.count > 0 %>
    <div class="d-flex justify-content-center mb-2">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
<% else %>
    <h1>データないよ</h1>
<% end %>

app/views/ramen_stores/new.html.erb
<%= render 'form', ramen_store: @ramen_store %>

app/views/ramen_stores/show.html.erb
<p><%= @ramen_store.store_name %></p>

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div class="field">
    <%= form.label :yubin %>
    <%= form.text_field :yubin %>
  </div>

  <div class="field">
    <%= form.label :num %>
    <%= form.text_field :num %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Yubin</th>
      <th>Num</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.adress %></td>
        <td><%= store.yubin %></td>
        <td><%= store.num %></td>
        <td><%= store.code %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @store.adress %>
</p>

<p>
  <strong>Yubin:</strong>
  <%= @store.yubin %>
</p>

<p>
  <strong>Num:</strong>
  <%= @store.num %>
</p>

<p>
  <strong>Code:</strong>
  <%= @store.code %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>